name: Publish image
on:
  push:
    branches:
      - main
      - feature/arm64
jobs:
  build-images:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Login to GitHub Package Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository }} --password-stdin
      - name: Install tooling
        run: |
          curl -L https://github.com/mikefarah/yq/releases/download/v4.2.1/yq_linux_amd64 > yq && chmod +x yq
          sudo cp -v yq /usr/bin/
          sudo apt-get install -y shellcheck
      # Setup OpenJDK 11
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11

      # Setup Maven cache
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build arm binary
        if: success()
        run: |
          export DOCKER_BUILD_ARGS="--platform linux/arm64 --cache-to=type=inline  --load"
          export DOCKER_BUILDX=buildx
          export DOCKER_ORG=${{ steps.repo-lowercase.outputs.lowercase }}
          export DOCKER_REGISTRY="ghcr.io"
          MVN_ARGS=-DskipTests make docker_build

